name: sql-query-ui
language: python
variables:
  - name: QUERY_API_URL
    inputType: FreeText
    description: URL of the DuckDB Query API service to connect to
    defaultValue: https://duckdb-peter-opcuademo-dev.app-staging.quix.io
    required: true
dockerfile: dockerfile
runEntryPoint: index.html
defaultFile: index.html
