name: basic-s3-sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the Kafka input topic to consume from
    required: true
  - name: S3_BUCKET
    inputType: FreeText
    description: S3 bucket name for storing Parquet files
    required: true
  - name: S3_BUCKET_DIRECTORY
    inputType: FreeText
    description: S3 bucket directory for storing Parquet files
    required: false
    defaultValue: ''
  - name: FILE_FORMAT
    inputType: FreeText
    description: file format to dump as
    required: true
    defaultValue: parquet
  - name: AWS_ACCESS_KEY_ID
    inputType: Secret
    description: AWS Access Key ID for S3 access
    required: false
    defaultValue: ""
  - name: AWS_SECRET_ACCESS_KEY
    inputType: Secret
    description: AWS Secret Access Key for S3 access
    required: false
  - name: AWS_REGION_NAME
    inputType: FreeText
    description: AWS region for S3 bucket
    defaultValue: us-east-1
    required: false
  - name: AWS_ENDPOINT_URL
    inputType: FreeText
    description: S3 endpoint url (for non-AWS endpoints)
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination